import GraphQLDataLoader from "../../src/lib/GraphQLDataLoader";

describe('GraphQLDataLoader', () => {
  describe('dispatchResult', () => {
    it('Check dispatchResult() result', () => {
      const result = {"getCategory_HMljEC_0_HMljEC_aliasCategory":{"name":"服务"},"getChina_HMljEC_0":{"englishName":"china","children":[{"name":"青海"},{"name":"天津"},{"name":"上海"},{"name":"北京"},{"name":"广东"},{"name":"辽宁"},{"name":"江苏"},{"name":"湖北"},{"name":"陕西"},{"name":"河北"},{"name":"山西"},{"name":"河南"},{"name":"吉林"},{"name":"黑龙江"},{"name":"内蒙古"},{"name":"山东"},{"name":"安徽"},{"name":"浙江"},{"name":"福建"},{"name":"湖南"},{"name":"广西"},{"name":"江西"},{"name":"贵州"},{"name":"云南"},{"name":"西藏"},{"name":"海南"},{"name":"甘肃"},{"name":"宁夏"},{"name":"新疆"},{"name":"四川"},{"name":"重庆"}]},"getUser_HMljEC_0":{"baseInfo":{"name":"上海熙月劳务派遣有限公司"}},"getCategory_HMljEC_1":{"name":"服务"},"getChina_HMljEC_1":{"englishName":"china","children":[{"name":"青海"},{"name":"天津"},{"name":"上海"},{"name":"北京"},{"name":"广东"},{"name":"辽宁"},{"name":"江苏"},{"name":"湖北"},{"name":"陕西"},{"name":"河北"},{"name":"山西"},{"name":"河南"},{"name":"吉林"},{"name":"黑龙江"},{"name":"内蒙古"},{"name":"山东"},{"name":"安徽"},{"name":"浙江"},{"name":"福建"},{"name":"湖南"},{"name":"广西"},{"name":"江西"},{"name":"贵州"},{"name":"云南"},{"name":"西藏"},{"name":"海南"},{"name":"甘肃"},{"name":"宁夏"},{"name":"新疆"},{"name":"四川"},{"name":"重庆"}]},"getUser_HMljEC_1":{"baseInfo":{"name":"兿朮傢x"}},"getUser_HMljEC_2":{"topbarInfo":{"hasWeishop":true}},"getAreaById_HMljEC_2":{"name":"上海"}};
      const separator = '_HMljEC_';
      expect(GraphQLDataLoader.dispatchResult(result, separator)).toMatchObject([{"aliasCategory":{"name":"服务"},"getChina":{"englishName":"china","children":[{"name":"青海"},{"name":"天津"},{"name":"上海"},{"name":"北京"},{"name":"广东"},{"name":"辽宁"},{"name":"江苏"},{"name":"湖北"},{"name":"陕西"},{"name":"河北"},{"name":"山西"},{"name":"河南"},{"name":"吉林"},{"name":"黑龙江"},{"name":"内蒙古"},{"name":"山东"},{"name":"安徽"},{"name":"浙江"},{"name":"福建"},{"name":"湖南"},{"name":"广西"},{"name":"江西"},{"name":"贵州"},{"name":"云南"},{"name":"西藏"},{"name":"海南"},{"name":"甘肃"},{"name":"宁夏"},{"name":"新疆"},{"name":"四川"},{"name":"重庆"}]},"getUser":{"baseInfo":{"name":"上海熙月劳务派遣有限公司"}}},{"getCategory":{"name":"服务"},"getChina":{"englishName":"china","children":[{"name":"青海"},{"name":"天津"},{"name":"上海"},{"name":"北京"},{"name":"广东"},{"name":"辽宁"},{"name":"江苏"},{"name":"湖北"},{"name":"陕西"},{"name":"河北"},{"name":"山西"},{"name":"河南"},{"name":"吉林"},{"name":"黑龙江"},{"name":"内蒙古"},{"name":"山东"},{"name":"安徽"},{"name":"浙江"},{"name":"福建"},{"name":"湖南"},{"name":"广西"},{"name":"江西"},{"name":"贵州"},{"name":"云南"},{"name":"西藏"},{"name":"海南"},{"name":"甘肃"},{"name":"宁夏"},{"name":"新疆"},{"name":"四川"},{"name":"重庆"}]},"getUser":{"baseInfo":{"name":"兿朮傢x"}}},{"getUser":{"topbarInfo":{"hasWeishop":true}},"getAreaById":{"name":"上海"}}]);
    });
  });
});
